### PR TITLE
removed unused construction and added CI

### PR DESCRIPTION
**Pull request by dark0ghost**

### CODE REVIEW

**Comment by MasterGroosha** [comment]
Hello! Thank you for the pull request! 
Could you please explain the purpose of this exact CI? 

Also please note that this repo is just a mirror, so I'll repeat your changes on GitLab which will sync with GitHub itself.

**Comment by dark0ghost** [comment]
This CI checks for vulnerabilities in the code.  It was added to prevent admission in the code of vulnerabilities

**Comment by MasterGroosha** [comment]
I guess it only works with GitHub, right?

**Comment by dark0ghost** [comment]
perhaps.  I don't use gitlab so I can't say for sure

**Pull request closed without merging**
